learning_rate: 0.0005
mbsize: 4
opt_beta: 0.9
opt_beta2: 0.999
opt_epsilon: 0.00000001
nemb: 256
min_blocks: 2
max_blocks: 8
num_iterations: 50000
num_conv_steps: 10
log_reg_c: 2.5e-5
reward_exp: 10
reward_norm: 8.0
sample_prob: 1.0
R_min: 0.0001
leaf_coef: 10.0
clip_grad: 0.0
clip_loss: 0.0
replay_mode: 'online'
bootstrap_tau: 0.0
weight_decay: 0.0 
random_action_prob: 0.05
array: ''
repr_type: 'block_graph'
model_version: 'v4'
run: 0
save_path: 'results/'
proxy_path: './data/pretrained_proxy'
print_array_length: False 
progress: 'yes'
floatX: 'float64'
include_nblocks: False
balanced_loss: True 
do_wrong_thing: False
obj: 'qed'