q_function: 'mlp'
atom_types: ["C", "O", "N"]
max_steps_per_episode: 40
init_mol: "C"
allow_removal: True
allow_no_modification: True
allow_bonds_between_rings: False 
allowed_ring_sizes: [5, 6]
fingerprint_radius: 2
fingerprint_length: 1024
discount_factor: 0.9
num_episodes: 20
replay_buffer_size: 500
batch_size: 32
double_q: True
gamma: 1.0
update_frequency: 3
num_bootstrap_heads: 6
prioritized: True
prioritized_alpha: 0.6
prioritized_beta: 0.4
prioritized_epsilon: 0.000001
save_frequency: 200
max_num_checkpoints: 10
q_function: "mlp"
distribution: False
noisy: False
dense_layers: [512]
activation: "ReLU"
optimizer: "Adam"
dropout: 0
batch_norm: False
learning_frequency: 4
learning_rate: 0.0001
learning_rate_decay_steps: 10000
learning_rate_decay_rate: 0.9
adam_beta_1: 0.9
adam_beta_2: 0.999
grad_clipping: 10
hidden_size: 300
bias: False
depth: 3
undirected: False
ffn_hidden_size: 300
ffn_num_layers: 2
atom_messages: False
features_only: False
use_input_features: True
features_dim: 1
no_cache: False
gen_number: 100
gen_epsilon: 0.1