proxy_learning_rate: 2.5e-4
proxy_dropout: 0.0
proxy_weight_decay: 0.000001
proxy_mbsize: 64
proxy_opt_beta: 0.9
proxy_nemb: 64
proxy_num_iterations: 10
num_init_examples: 2000
num_outer_loop_iters: 25
num_samples: 200
proxy_num_conv_steps: 12
proxy_repr_type: 'atom_graph'
proxy_model_version: 'v2'
progress: False
learning_rate: 0.0005
opt_beta: 0.9
opt_beta2: 0.999
opt_epsilon: 0.00000001
nemb: 256
mbsize: 4
min_blocks: 2
max_blocks: 8
num_iterations: 50000
num_conv_steps: 10
log_reg_c: 0.00000002
sample_prob: 1.0
R_min: 0.0001
leaf_coef: 10.0
clip_grad: 0.0
clip_loss: 0.0
replay_mode: 'online'
bootstrap_tau: 0.0
weight_decay: 0.0 
random_action_prob: 0.05
repr_type: 'block_graph'
include_nblocks: False
model_version: 'v4'
save_path: 'gflownet_models/'
proxy_path: './data/pretrained_proxy'
floatX: 'float64'
balanced_loss: True 
run: 0
array: ''